project:
  type: website
  output-dir: docs

website:
  title: "June Lynn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: abuot.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



